version: "3"
services:
  bot:
    image: orlea/hogire:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    env_file: .env
    volumes:
      - /mnt/efs/emoji:/data
    command: "node src/app.js"
